tomey:
  width: X(Width)=
  height: Z(Depth)=
  imageCount: Y(Height)=
  bytesPerPixel: VoxelBits=
  fileName: FILESTOREFILENAME1=
  fileName2: FILESTOREFILENAME2=
  imageOffset: 232
  targetImageFormat: png
  patient:
    id: Patient ID=
    firstName: First name=
    lastName: Family Name=
    birthday: Date of Birth=
    eye: Eye=
    commentary: Description=
