tomey:
  width: X(Width)=
  height: Z(Depth)=
  imageCount: Y(Height)=
  bitsPerPixel: VoxelBits=
  fileName: FILESTOREFILENAME1=
  fileName2: FILESTOREFILENAME2=
  imageOffset: 232
  targetImageFormat: png
  xSizeInMM: X range in V=
  ySizeInMM: Y range in V=
  zSizePerPixel: MmPerPixZ=
  examinationDate: Date=
  examinationTime: Time=
  eyeImageFirstHeaderOffset: 233
  eyeImageHeaderSize: 284
  eyeImageInHeaderHeightPosition: 260
  eyeImageInHeaderWidthPosition: 264
  eyeImageContentOffset: 260
  patient:
    id: Patient ID=
    firstName: First name=
    lastName: Family Name=
    birthday: Date of Birth=
    eye: Eye=
    commentary: Description=
